### PR TITLE
Refactor examples

### PR DESCRIPTION
**Pull request by grimradical**
The examples on the landing page lacked CSS and were a bit busy, but
they're still awesome. I re-framed them into a "wash by example"
section, with a link to the tutorial at the end.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Can you add the DCO signoff to the commit?

**Comment by MikaelSmith** [comment]
I think this works for shortening it up.

**Review by ekinanp — APPROVED** [review]

**Review by MikaelSmith — APPROVED** [review]
I'm good with this once it passes the DCO check.

**Comment by grimradical** [comment]
DCO check passes now, thanks for the reminder!

**Pull request merged**
