### PR TITLE
Make Wash ls more symmetric with the built-in ls

### PR DESCRIPTION
**Pull request by ekinanp**
The commits contain all the details.

### CODE REVIEW

**Comment by ekinanp** [comment]
Here's what the new `ls` looks like:

```
wash . ❯ ls docker/containers/wash_tutorial_redis_1
fs/
log
metadata.json
wash . ❯ ls -l docker/containers/wash_tutorial_redis_1
NAME            MODIFIED    ACTIONS
fs/             <unknown>   list
log             <unknown>   read, stream
metadata.json   <unknown>   read
wash . ❯ ls docker/containers/wash_tutorial_redis_1/metadata.json
metadata.json
```

**Comment by ekinanp** [comment]
I'm not yet sure how to handle "hidden" entries. I considered defining them as entries whose cname begins with a `.`, but a definition like that's a bit too early so I left it out for now.

**Comment by MikaelSmith** [comment]
Does that mean "hidden" files will always be shown?

**Review by MikaelSmith — CHANGES_REQUESTED** [review]
This looks good. Can you also update the website to reflect the changes to `ls`? In particular I'm thinking about how it prints errors.

**Comment by ekinanp** [comment]
For now, yeah. Hidden files will also be included.

**Comment by ekinanp** [comment]
And ah yeah, I forgot about the website. Will do.

**Review by MikaelSmith — APPROVED** [review]

**Pull request merged**
